# Generated by Django 4.1.7 on 2023-05-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('marque', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('prix', models.FloatField()),
            ],
        ),
    ]
