# Generated by Django 4.1.7 on 2023-05-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarsapp', '0002_voiture_nb_passager_voiture_nb_portes'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='carburant',
            field=models.CharField(choices=[('essance', 'ESSENCE'), ('diesel', 'DIESEL')], default='diesel', max_length=10),
        ),
    ]
