# Generated by Django 4.2 on 2023-05-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarsapp', '0003_voiture_carburant'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
