# Generated by Django 4.1.7 on 2023-05-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarsapp', '0004_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
