# Generated by Django 4.2 on 2023-05-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarsapp', '0004_voiture_image'),
        ('rentcarsapp', '0005_delete_client'),
    ]

    operations = [
    ]
