# Generated by Django 4.2 on 2023-05-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarsapp', '0009_reservation_datereservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='datefin',
            new_name='dateFin',
        ),
    ]
