# Generated by Django 4.2 on 2023-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarsapp', '0010_rename_datefin_reservation_datefin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paye',
            field=models.BooleanField(default=False),
        ),
    ]
